# Generated by Django 5.2.1 on 2025-05-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'partial_pay'), (3, 'fully_pay')], default=0, null=True),
        ),
    ]
