# Generated by Django 5.2.1 on 2025-05-20 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('carts', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='fixed', max_length=20)),
                ('expiry', models.DateTimeField()),
                ('limit', models.PositiveIntegerField()),
                ('used_counts', models.PositiveIntegerField(default=0)),
                ('active_status', models.IntegerField(choices=[(1, 'Live'), (0, 'finished')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_categories', models.ManyToManyField(blank=True, related_name='coupons', to='products.category')),
                ('applicable_products', models.ManyToManyField(blank=True, related_name='coupons', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='cuppons.coupon')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to='carts.order')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_coupons_products', to='carts.orderitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_coupons', to='accounts.userprofile')),
            ],
            options={
                'unique_together': {('coupon', 'user', 'order_item')},
            },
        ),
    ]
