# Generated by Django 5.2.1 on 2025-05-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('carts', '0004_alter_order_payment_status'),
        ('cuppons', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'user', 'order_item', 'order')},
        ),
    ]
