# Generated by Django 5.2.1 on 2025-05-21 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('carts', '0004_alter_order_payment_status'),
        ('cuppons', '0002_alter_couponusage_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='couponusage',
            unique_together={('coupon', 'user', 'order')},
        ),
        migrations.RemoveField(
            model_name='couponusage',
            name='order_item',
        ),
    ]
